### PR TITLE
Li_W PS2

### PR DESCRIPTION
**Pull request by weijia1995**
Dear Dr. Evans,

Please find the updated PS2 documents

Many Thanks.
Weijia

### CODE REVIEW

**Comment by rickecon** [comment]
@weijia1995 . You don't have to submit a new PR. When you push your commits to your remote branch, it automatically adds those commits to this PR. What is your question?

**Comment by weijia1995** [comment]
@rickecon I was writing a fsolve function in TPI file to solve bvec = [b(2,t), b(3,t+1)] and I think it supposes to generate T lots of solutions but it only gave me one solution. I just couldn't figure out what went wrong.

**Comment by weijia1995** [comment]
I tried to finish the code and I did finally get some outputs, yet I don't think the numbers are right and still working on debugging...

**Comment by rickecon** [comment]
@weijia1995 you can look at Luke and Alex's code by going to their pull requests and examining what they did. Don't copy it wholesale, but make your code do what theirs does.

**Pull request merged**
