### PR TITLE
Renewed question

### PR DESCRIPTION
**Pull request by magicahan**
Sorry, rick! I create a a new pull request, since there's something wrong with the last one, where I didn't updated it successfully.

### CODE REVIEW

**Comment by magicahan** [comment]
The renewed version seems to be a correct one

**Comment by magicahan** [comment]
@rickecon  If you run the p3_script file, it will import the p3_func file. I initialize all of the parameters in a different file

**Comment by rickecon** [comment]
@magicahan . Is it in the "Renew Version" folder, or is it the two files right under your "Questions" folder?

**Comment by rickecon** [comment]
@magicahan . I'll bet it is a problem with the parameters that you are passing around throughout your code. It is very difficult to keep track in your code of what parameters are being passed into each function. Things you should check include making sure that all the parameters that you are unpacking are the parameters you think you are unpacking. One good practice is to re-declare a parameters tuple right before you call the function for which they are inputs.

**Comment by rickecon** [comment]
@magicahan. You clearly have an error in your code somewhere, and we are trying to find out where it is. It is very difficult to do this when you don't know what exactly was input into a function. For example, in lines 60-62 of `Pset_3_func.py` you unpack the following parameters.
```python
    alpha = params[3]
    A = params[2]
    nvec = params[1]
``` 
However, to figure out what is in that `params` object, I have to go back through `f_params` in the `feasible()` function, then to line 30 of the `Pset_3_script.py` file. Following this thread, I noticed that your `f_params` declaration in line 30 of the `Pset_3_script.py` puts objects of different types in that numpy array. You can't do this. Python's tuple object is what you need to hold objects of different types (e.g., vectors, scalars, strings, dictionaries). I suggest making your parameter vectors tuples.
```python
f_params = (S, nvec, A, alpha, delta, beta)
```

**Comment by rickecon** [comment]
@magicahan . I also noticed in lines 63-64 of `Pset_3_func.py` that you compute the aggregate labor `L` and aggregate capital `K` as sums.
```python
L = sum(nvec)
K = sum(bvec)
```
You do this despite the fact that you have defined functions earlier in your code `get_L()` and `get_K()` that do this same thing. A better approach for lines  63-64 of `Pset_3_func.py` would be to call those functions. That way, if you needed to change those functions, you only have to do it in one place.

**Comment by magicahan** [comment]
@rickecon 
Thank you Rick! The reason why I have the conflicts in the parameters is because f_params is different from params. That is why I don't make them uniform.
I make changes to the file where I use params for f_params, just to make it more uniform.
But it still doesn't work. I think the root finder and my code are compatible with each other.

**Comment by magicahan** [comment]
@rickecon   I just update my code and make all of the parameters to take the following form, and it still doesn't work 
S,  nvec, A, alpha, delta, beta, sigma, L, SS_tol = params
Sorry for the unreadability, you forget to change things when stuff gets unwieldy.
P.S (Pset_3_func.py is function file;   Pset_3_script.py is where I initialize all of the parameters.)

**Comment by magicahan** [comment]
@rickecon 
Hi Rick! I finally figured out where is the issue!!!
It's the stupidest mistake I've ever made.
I have the wrong initial beta and delta value. I thought this was the same from the 3 period problem
So sorry for the trouble!

**Comment by rickecon** [comment]
@magicahan . When I run your file `Pset_3_script.py`, I get the following error:
```
Traceback (most recent call last):
  File "Pset_3_script.py", line 80, in <module>
    f_3 = p3.feasible(f_params, bvec_guess3)
  File "/Users/rwe/Documents/Economics/Teaching/MACSS/MACS40000_OG/OGcourse_F16/Students/HanL/Questions/Renew Version/Pset_3_func.py", line 161, in feasible
    S,  nvec, A, alpha, delta, beta, sigma, L, SS_tol = params
ValueError: not enough values to unpack (expected 9, got 6)
```
In line 160 of your `feasible()` function in `Pset_3_func.py, there are 9 items to unpack from your `params` input. However, in line 80 of `Pset_3_script.py` you use the `f_params` vector (declared on line 30) as your input to the `feasible` function. I think you meant to use the `params` vector declared in line 34. However, you still need to use tuples and not arrays, as I mentioned in my last comment.

**Pull request merged**
